### ISSUE TITLE
Custom Order - fails with "You can only favorite a single file or folder at a time"

### ISSUE THREAD

**Issue by eurodrew555** [newhinton/quickaccesssorting#1]
This App looks great for sorting Favorites, however it doesn't save the new custom order.
Every time I try to re-order it has an error "You can only favorite a single file or folder at a time".
When I refresh the page the order has not been saved.

I'm using Nextcloud 16.0.4

**Comment by newhinton** [comment]
I can confirm this behaviour, i will try to fix it soon

**Comment by newhinton** [comment]
@eurodrew555 I fixed that. Sorry it took so long

**Comment by eurodrew555** [comment]
Hi @newhinton I am currently on 19.0.4.
I have installed Favorites Quickaccess Sorting 1.0.3 but I'm still seeing the same issue?

**Comment by newhinton** [comment]
i updated it to nc20, so it should be available with the next version. i am currently implementing translations, i will look into backporting this to nc19 since there are some minor breaking changes between those two versions

**Comment by eurodrew555** [comment]
No worries, will look forward to seeing it in nc20.
Thanks a lot for fixing it!

**Comment by newhinton** [comment]
@eurodrew555 It should be available for nc19 aswell, including support for translations (currently de&en)
